### PR TITLE
Add Nexus 6P (angler) repository

### PR DESCRIPTION
**Pull request by zhuowei**

### CODE REVIEW

**Comment by goold10004** [comment]
https://youtu.be/rVB5TMcAMBg

**Comment by zhuowei** [comment]
@Tasssadar Please merge this: we've added the manifest to our own repo and tested this change; recovery, multirom, and kernel all show up.

**Comment by Tasssadar** [comment]
Thanks! Version 1.188 will be on Play store in a few hours.
Are you considering merging the 6P changes to my tree?

**Comment by npjohnson** [comment]
Yes, I'll get the commits together and send them over tonight (:

**Comment by HashBang173** [comment]
https://github.com/Tasssadar/multirom/pull/76

**Pull request merged**
