### PR TITLE
Add support for ZTE V5 RedBull (X9180)

### PR DESCRIPTION
**Pull request by proDOOMman**
Hello. I made a fully working port of MultiROM for ZTE V5 RedBull. Can you add my manifest to MultiROMMgr?

### CODE REVIEW

**Comment by proDOOMman** [comment]
Hello?

**Comment by Tasssadar** [comment]
Hey, sorry it took so long for me to get to this. Can you test this build, see if everything works correctly on the device? http://tasemnice.eu/bordel/MultiROMMgr-v1.175-zteredbulltest.apk

**Comment by proDOOMman** [comment]
All works fine.

**Comment by Tasssadar** [comment]
Merged.

**Pull request closed without merging**
